### ISSUE TITLE
[Oct-Jan][Backlog] Curation Workflow Tracking

### ISSUE THREAD

**Issue by aditigopalan** [mc2-center/data-models#85]
This ticket tracks the upload of tools and datasets into the portal. 

As of 3/6/2024, the portal is update with publications from October - January. Datasets have been uploaded for June - November. Portal sync pending for tools and dataset. I anticipate this will be synced and updated with the next portal sync

Status Check: 
- [x] **Upload datasets** 
    - [x] September
    - [x] October
    - [x] November [14]
    - [x] December [8]
    - [x] January
    - [x] February

- [x] **Upload tools**
    - [x] September
    - [x] October
    - [x] November 
    - [x] December 
    - [x] January
    - [x] February

- [x] Perform portal sync

**Comment by aditigopalan** [comment]
@Bankso I remember we were tracking a minimal data model for annotation on a ticket, is that still open?

**Comment by Bankso** [comment]
@aditigopalan I think we closed that one, but we did integrate some changes in the requirements for DatasetView as part of that ticket. 

For defining the minimal metadata requirements, I think we could have a ticket for each of the schemas, since we will likely work on them at different times and there will be different considerations for each.
